#Maven Build
FROM maven:latest AS build

# Define ALL environment variables here
ARG MONGO_URI
ARG SPRING_MAIL_USERNAME
ARG SPRING_MAIL_PASSWORD
ARG SPRING_THYMELEAF_CACHE
ARG CLOUDINARY_CLOUD_NAME
ARG CLOUDINARY_API_KEY
ARG CLOUDINARY_API_SECRET
ARG AGREEMENT_UPLOAD_LINK
ARG PAYMENT_PROCESS_LINK
ARG JWT_SECRET_KEY
ARG JWT_EXPIRATION
ARG PUBLIC_PATTERNS
ARG JWT_CLIENT_ID
ARG ALLOWED_ORIGINS
ARG CC_EMAIL_LIST

# Set environment variables
ENV MONGO_URI=$MONGO_URI \
    SPRING_MAIL_USERNAME=$SPRING_MAIL_USERNAME \
    SPRING_MAIL_PASSWORD=$SPRING_MAIL_PASSWORD \
    SPRING_THYMELEAF_CACHE=$SPRING_THYMELEAF_CACHE \
    CLOUDINARY_CLOUD_NAME=$CLOUDINARY_CLOUD_NAME \
    CLOUDINARY_API_KEY=$CLOUDINARY_API_KEY \
    CLOUDINARY_API_SECRET=$CLOUDINARY_API_SECRET \
    AGREEMENT_UPLOAD_LINK=$AGREEMENT_UPLOAD_LINK \
    PAYMENT_PROCESS_LINK=$PAYMENT_PROCESS_LINK \
    JWT_SECRET_KEY=$JWT_SECRET_KEY \
    JWT_EXPIRATION=$JWT_EXPIRATION \
    PUBLIC_PATTERNS=$PUBLIC_PATTERNS \
    JWT_CLIENT_ID=$JWT_CLIENT_ID \
    ALLOWED_ORIGINS=$ALLOWED_ORIGINS \
    CC_EMAIL_LIST=$CC_EMAIL_LIST

COPY src /usr/src/app/src

COPY pom.xml /usr/src/app

RUN mvn -f /usr/src/app/pom.xml clean package

FROM openjdk:17

COPY --from=build /usr/src/app/target/jeffjackson-1.9.jar /usr/app/jeffjackson-1.9.jar

EXPOSE 5151

CMD ["java", "-jar", "/usr/app/jeffjackson-1.9.jar"]